import{getApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import{getFirestore,collection,getDocs,addDoc,doc,setDoc,updateDoc,deleteDoc,onSnapshot}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';

const sleep=m=>new Promise(r=>setTimeout(r,m));
async function fb(){for(let i=0;i<80;i++){try{const a=getApp();return{auth:getAuth(a),db:getFirestore(a)}}catch{}await sleep(100)}throw Error('Firebase not ready')}
function cutoff(){const d=new Date();d.setMonth(d.getMonth()-3);return d.getTime()}
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function dateKeyFromMs(ms){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Number(ms)||Date.now()))}

function parts(v){let s=String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/\bAPARTMENT\b/g,'APT').replace(/\bUNIT\b/g,'APT').replace(/\bSUITE\b/g,'APT').replace(/\bSTE\b/g,'APT').replace(/\bNORTH\b/g,'N').replace(/\bSOUTH\b/g,'S').replace(/\bEAST\b/g,'E').replace(/\bWEST\b/g,'W');let apt='';const p=s.search(/(?:\bAPT\b|#)/);if(p>=0){const a=s.slice(p).replace(/^(?:APT|#)\s*/,'').replace(/[^A-Z0-9\s-]/g,' ').trim().split(/\s+/);apt=(a[0]||'').replace(/[^A-Z0-9]/g,'');if(a[1]&&/^\d$/.test(a[0])&&/^\d$/.test(a[1]))apt+=a[1];s=s.slice(0,p)}s=s.replace(/[^A-Z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();const t=s.split(' ').filter(Boolean),number=(t.shift()||'').replace(/[^A-Z0-9-]/g,'');const types=new Set(['ST','STREET','AVE','AV','AVENUE','BLVD','BOULEVARD','RD','ROAD','DR','DRIVE','LN','LANE','CT','COURT','CIR','CIRCLE','PKWY','PARKWAY','HWY','HIGHWAY','PL','PLACE','TER','TERRACE','WAY','TRL','TRAIL']);const x=t.findIndex(z=>types.has(z)),street=(x>=0?t.slice(0,x):t).join('').replace(/[^A-Z0-9]/g,'');return{number,street,apt}}
export function addressKey(v){const p=parts(v);return p.number&&p.street?`${p.number}|${p.street}|${p.apt||''}`:''}
export function formatDate(ms){return ms?new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(ms)):'Date unavailable'}
export const label=a=>({new:'Added',existing:'Existing record',duplicate_pending:'Duplicate attempt',duplicate_cancel:'Duplicate · Cancelled',duplicate_overwrite:'Duplicate · Overwritten',duplicate_add:'Duplicate · Notes added'})[a]||a||'Added';
export const store={complaints:[],events:[],hits:[],routes:[],user:null};
const safe=s=>btoa(unescape(encodeURIComponent(s))).replace(/[+/=]/g,'_').slice(0,1300);

async function clean(db){for(const n of['complaintEvents','routeHits']){const s=await getDocs(collection(db,n));await Promise.all(s.docs.filter(x=>Number(x.data().createdMs||0)<cutoff()).map(x=>deleteDoc(x.ref).catch(()=>{})))}}
async function seed(db){const[c,e]=await Promise.all([getDocs(collection(db,'complaints')),getDocs(collection(db,'complaintEvents'))]),known=new Set(e.docs.map(x=>x.data().complaintId).filter(Boolean));for(const x of c.docs){if(known.has(x.id))continue;const d=x.data(),k=addressKey(d.address),ms=Number(d.updatedMs||0)||Date.now();if(k&&ms>=cutoff())await setDoc(doc(db,'complaintEvents',`baseline_${x.id}`),{complaintId:x.id,addressKey:k,address:d.address||'',notes:d.notes||'',action:'existing',createdMs:ms,dateKey:dateKeyFromMs(ms),assignedWeekStart:'',actorUid:store.user?.uid||''},{merge:true})}}

let busy=false,again=false;
async function routeHits(db){if(busy){again=true;return}busy=true;try{for(const r of store.routes){const dateKey=r.dateKey||today(),ms=Date.parse(`${dateKey}T12:00:00`);if(ms<cutoff())continue;const wanted=new Map;for(const st of r.stops||[]){const k=addressKey(st.address),c=store.complaints.find(q=>addressKey(q.address)===k);if(!k||!c)continue;const id=safe(`${r.id}|${dateKey}|${r.driverId}|${st.stop}|${k}`);wanted.set(id,{routeDocId:r.id,complaintId:c.id,addressKey:k,address:st.address||c.address||'',driverId:r.driverId||'',driverName:r.driverName||'',stop:st.stop??'',dateKey,createdMs:Number.isFinite(ms)?ms:Date.now()})}await Promise.all(store.hits.filter(h=>h.routeDocId===r.id&&!wanted.has(h.id)).map(h=>deleteDoc(doc(db,'routeHits',h.id)).catch(()=>{})));await Promise.all([...wanted].map(([id,d])=>setDoc(doc(db,'routeHits',id),d,{merge:true})))}}finally{busy=false;if(again){again=false;setTimeout(()=>routeHits(db),150)}}}

export function recent(a){return a.filter(x=>Number(x.createdMs||0)>=cutoff())}
export async function initAnalytics(onChange){const{auth,db}=await fb();onAuthStateChanged(auth,async u=>{if(!u)return;store.user=u;await clean(db).catch(()=>{});await seed(db).catch(()=>{});onSnapshot(collection(db,'complaints'),s=>{store.complaints=s.docs.map(x=>({id:x.id,...x.data()}));onChange();routeHits(db).catch(()=>{})});onSnapshot(collection(db,'complaintEvents'),s=>{store.events=s.docs.map(x=>({id:x.id,...x.data()}));onChange()});onSnapshot(collection(db,'routeHits'),s=>{store.hits=s.docs.map(x=>({id:x.id,...x.data()}));onChange()});onSnapshot(collection(db,'routes'),s=>{store.routes=s.docs.map(x=>({id:x.id,...x.data()}));routeHits(db).catch(()=>{})})});return db}
export async function addAttempt(db,address,notes,existing,assignedWeekStart=''){return addDoc(collection(db,'complaintEvents'),{complaintId:existing?.id||'',addressKey:addressKey(address),address,notes,action:existing?'duplicate_pending':'new',createdMs:Date.now(),dateKey:today(),assignedWeekStart,actorUid:store.user?.uid||''})}
export async function finishAttempt(ref,action){if(ref)await updateDoc(ref,{action:`duplicate_${action}`})}
