import{getApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{getFirestore,collection,getDocs,addDoc,doc,setDoc,deleteDoc,serverTimestamp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';

const sleep=m=>new Promise(r=>setTimeout(r,m));
async function dbReady(){for(let i=0;i<80;i++){try{return getFirestore(getApp())}catch{}await sleep(100)}throw Error('Firebase not ready')}
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().replace(/\s+/g,' ').toUpperCase();
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(msg){const t=document.getElementById('toast');if(t){t.textContent=msg;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),3500)}else alert(msg)}
function csvRows(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function namesFromCsv(text){const rows=csvRows(text.replace(/^\uFEFF/,''));return [...new Map(rows.slice(1).map(r=>String(r[0]||'').trim()).filter(Boolean).map(n=>[norm(n),n])).values()]}
async function syncStation(station,file){if(!file)return;const names=namesFromCsv(await file.text());if(!names.length)throw Error('No drivers found in column A starting at row 2.');const db=await dbReady();const snap=await getDocs(collection(db,'drivers'));const drivers=snap.docs.map(x=>({id:x.id,...x.data()}));const byName=new Map(drivers.map(d=>[norm(d.name),d]));for(const name of names){const k=norm(name),old=byName.get(k);if(old){await setDoc(doc(db,'drivers',old.id),{name,station,updatedAt:serverTimestamp()},{merge:true})}else{const ref=await addDoc(collection(db,'drivers'),{name,station,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});byName.set(k,{id:ref.id,name,station})}}
await setDoc(doc(db,'driverSyncMeta',station),{station,names:names.map(norm),count:names.length,syncedAt:serverTimestamp(),syncedMs:Date.now()},{merge:true});
const meta=await getDocs(collection(db,'driverSyncMeta'));const stations=new Map(meta.docs.map(x=>[x.id,x.data()]));let removed=0;if(stations.has('DJX3')&&stations.has('DJX4')){const keep=new Set([...(stations.get('DJX3').names||[]),...(stations.get('DJX4').names||[])]);const fresh=await getDocs(collection(db,'drivers'));for(const x of fresh.docs){if(!keep.has(norm(x.data().name))){await deleteDoc(x.ref);removed++}}}else{const fresh=await getDocs(collection(db,'drivers'));for(const x of fresh.docs){const d=x.data();if(d.station===station&&!names.some(n=>norm(n)===norm(d.name))){await deleteDoc(x.ref);removed++}}}
toast(`${station}: ${names.length} drivers synchronized${removed?` · ${removed} removed`:''}.`);setTimeout(()=>location.reload(),700)}
function buildUI(){const page=document.getElementById('drivers');if(!page||document.getElementById('driverSyncPanel'))return;const card=page.querySelector('.card');const header=card?.querySelector('.row.between');const add=document.getElementById('addDriverBtn');if(add)add.classList.add('hide');const panel=document.createElement('div');panel.id='driverSyncPanel';panel.innerHTML=`<div style="margin-top:14px;padding:14px;border:1px solid #dbe8f2;border-radius:17px;background:#fbfdff"><div style="font-weight:900;margin-bottom:4px">Synchronize drivers from roster</div><div class="muted" style="margin-bottom:12px">Upload the DJX3 or DJX4 CSV. COACH reads driver names from column A starting at row 2.</div><div class="row"><label class="btn blue" style="display:inline-block">Sync DJX3<input id="syncDJX3" type="file" accept=".csv,text/csv" hidden></label><label class="btn blue" style="display:inline-block">Sync DJX4<input id="syncDJX4" type="file" accept=".csv,text/csv" hidden></label></div><div id="syncStatus" class="muted" style="margin-top:10px"></div></div>`;header?.insertAdjacentElement('afterend',panel);
const search=document.createElement('div');search.id='driverSearchPanel';search.className='field';search.style.margin='14px 0';search.innerHTML='<input id="driverSearch" type="search" placeholder="Search driver by name..." autocomplete="off" style="width:100%">';
panel.insertAdjacentElement('afterend',search);
const filterDrivers=()=>{const q=norm(document.getElementById('driverSearch')?.value||'');const list=document.getElementById('driversList');if(!list)return;[...list.children].forEach(item=>{const name=norm(item.querySelector('.drivername')?.textContent||item.textContent||'');item.style.display=!q||name.includes(q)?'':''})};
document.getElementById('driverSearch')?.addEventListener('input',filterDrivers);
new MutationObserver(filterDrivers).observe(document.getElementById('driversList')||document.body,{childList:true,subtree:true});
filterDrivers();
for(const st of['DJX3','DJX4'])document.getElementById(`sync${st}`)?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;const status=document.getElementById('syncStatus');status.textContent=`Synchronizing ${st}...`;try{await syncStation(st,f)}catch(err){console.error(err);status.textContent='';toast(err.message||'Could not synchronize drivers.')}finally{e.target.value=''}})}
function start(){buildUI();new MutationObserver(buildUI).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
